FROM python:3.8
ENTRYPOINT [pytest]

COPY . /datadog-api-client-python
WORKDIR /datadog-api-client-python/
RUN pip wheel --wheel-dir=/tmp/wheelhouse .[tests] && pip install --no-index --find-links=/tmp/wheelhouse datadog-api-client[tests]

