site_name: Datadog API Client for Python
site_description: The home of Datadog API Python Client documentation
site_author: Datadog
site_url: https://datadoghq.dev/datadog-api-client-python/
repo_name: datadog/datadog-api-client-python
repo_url: https://github.com/DataDog/datadog-api-client-python
edit_uri: blob/master/docs
copyright: 'Copyright &copy; Datadog, Inc. 2020-present'

docs_dir: docs
site_dir: site
theme:
  name: material
  language: en
#  features:
#    - navigation.tabs
    # https://github.com/facelessuser/pymdown-extensions/issues/876#issuecomment-610164436
    # - navigation.instant
  palette:
    scheme: slate
    primary: deep purple
    accent: deep purple
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github-alt
  favicon: assets/images/favicon.ico
  logo: assets/images/logo.svg

nav:
  - API:
      - 'Version 1': v1/
      - 'Version 2': v2/

plugins:
  # Built-in
  - search:
  # Extra
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_if_no_docstring: yes
            show_root_heading: yes
            show_source: true

extra:
  social:
    - icon: fontawesome/solid/blog
      link: https://www.datadoghq.com/blog/engineering/
    - icon: fontawesome/brands/github-alt
      link: https://github.com/DataDog
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/datadoghq
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/datadoghq