# Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2019-Present Datadog, Inc.


from datadog_api_client.v2.model_utils import (
    ModelNormal,
    cached_property,
)


class LogsArchiveIntegrationGCS(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    validations = {}

    @cached_property
    def openapi_types():
        return {
            "client_email": (str,),
            "project_id": (str,),
        }

    attribute_map = {
        "client_email": "client_email",
        "project_id": "project_id",
    }

    read_only_vars = {}

    def __init__(self, client_email, project_id, *args, **kwargs):
        """LogsArchiveIntegrationGCS - a model defined in OpenAPI

        Args:
            client_email (str): A client email.
            project_id (str): A project ID.

        Keyword Args:
        """
        super().__init__(kwargs)

        self._check_pos_args(args)

        self.client_email = client_email
        self.project_id = project_id

    @classmethod
    def _from_openapi_data(cls, client_email, project_id, *args, **kwargs):
        """Helper creating a new instance from a response."""

        self = super(LogsArchiveIntegrationGCS, cls)._from_openapi_data(kwargs)

        self._check_pos_args(args)

        self.client_email = client_email
        self.project_id = project_id
        return self
