name: Send PR Approval Status

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - master
    types: ["review_requested", "synchronize", "opened", "reopened"]
  pull_request_review:
    types:
      - submitted
      - dismissed

jobs:
  send_status:
    runs-on: ubuntu-latest
    if: >
      github.event.pull_request.draft == false &&
      !contains(github.event.pull_request.labels.*.name, 'ci/skip') &&
      !contains(github.event.pull_request.head.ref, 'datadog-api-spec/test/') &&
      contains(github.event.pull_request.head.ref, 'datadog-api-spec/generated/')
    permissions:
      id-token: write
    steps:
      - name: Get GitHub App token
        id: get_token
        uses: DataDog/dd-octo-sts-action@96a25462dbcb10ebf0bfd6e2ccc917d2ab235b9a # v1.0.4
        with:
          scope: DataDog/datadog-api-spec
          policy: datadog-api-client-python.approved_status.post-review-status
      - name: Post PR review status check
        uses: DataDog/github-actions/post-review-status@v2
        with:
          github-token: ${{ steps.get_token.outputs.token }}
          repo: datadog-api-spec
          context: datadog-api-client-python/master
