name: Run Tests

permissions:
  contents: read

env:
  GIT_AUTHOR_EMAIL: "packages@datadoghq.com"
  GIT_AUTHOR_NAME: "ci.datadog-api-spec"

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 2 * * *"

concurrency:
  group: unit-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    if: >
      (github.event.pull_request.draft == false &&
       !contains(github.event.pull_request.labels.*.name, 'ci/skip') &&
       !contains(github.event.pull_request.head.ref, 'datadog-api-spec/test/')) ||
      github.event_name == 'schedule'
    uses: ./.github/workflows/reusable-pre-commit.yml
    permissions:
      id-token: write
      contents: read
    with:
      enable-commit-changes: true

  test:
    if: >
      (github.event.pull_request.draft == false &&
       !contains(github.event.pull_request.labels.*.name, 'ci/skip') &&
       !contains(github.event.pull_request.head.ref, 'datadog-api-spec/test/')) ||
      github.event_name == 'schedule'
    uses: ./.github/workflows/reusable-python-test.yml
    with:
      python-versions: '["3.8", "3.12"]'
      platforms: '["ubuntu-22.04", "ubuntu-latest", "macos-latest"]'
      matrix-exclude: '[{"platform": "macos-latest", "python-version": "3.8"}, {"platform": "ubuntu-latest", "python-version": "3.8"}, {"platform": "ubuntu-22.04", "python-version": "3.12"}]'

  examples:
    if: >
      (github.event.pull_request.draft == false &&
       !contains(github.event.pull_request.labels.*.name, 'ci/skip') &&
       !contains(github.event.pull_request.head.ref, 'datadog-api-spec/test/')) ||
      github.event_name == 'schedule'
    uses: ./.github/workflows/reusable-examples.yml
    with:
      examples-script: './check-examples.sh'
      python-version: '3.12'

  report:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    if: always() && github.event_name == 'pull_request' && contains(github.event.pull_request.head.ref, 'datadog-api-spec/generated/')
    needs:
      - test
      - examples
    steps:
      - name: Get dd-octo-sts token
        id: octo-sts
        uses: DataDog/dd-octo-sts-action@96a25462dbcb10ebf0bfd6e2ccc917d2ab235b9a # v1.0.4
        with:
          scope: DataDog/datadog-api-spec
          policy: datadog-api-client-python.github.post-status-check.pull-request
      - name: Post status check
        uses: DataDog/github-actions/post-status-check@v2
        with:
          github-token: ${{ steps.octo-sts.outputs.token }}
          repo: datadog-api-spec
          status: ${{ (needs.test.result == 'cancelled' || needs.examples.result == 'cancelled') && 'pending' || (needs.test.result == 'success' && needs.examples.result == 'success') && 'success' || 'failure' }}
          context: master/unit
